% Author: Utkarsh Patel (18EC30048)
% Experiment - 1 Part D (Run on MATLAB online)
% Interpolation and upsampling

Fs = 12000;  % Sampling frequency
N = 256;     % Number of samples for FFT
Nf = 2*N;    % Samples required after zero embedding
t = 0 : 1/Fs : (N-1)/Fs; % time range
s = 10 * cos(2 * pi * 1000 * t) + 6 * cos(2 * pi * 2000 * t) + 2 * cos(2 * pi * 4000 * t); % signal used for this experiment
y = upsample(s,2); % upsampling singal 's' by zero embedding

% Filter design
d = designfilt('lowpassfir', 'FilterOrder', 20, 'CutoffFrequency', 6000, 'SampleRate', 24000); % Specification of filter
y_f = filter(d, y);             % filtering the 'upsampled' signal
y_fft = abs(fft(y_f))/(Nf);     % FFT of filtered signal
t1 = 0:1/(2*Fs):(Nf-1)/(2*Fs);
s1 = 10*cos(2*pi*1000*t1) + 6*cos(2*pi*2000*t1) + 2*cos(2*pi*4000*t1); % Sampling @ 24 KHz
s1_fft = abs(fft(s1)) / (Nf);
f = -Fs : 2 * Fs / (Nf - 1) : Fs; % frequency range for DFT

subplot(2, 1, 1);
plot(f, y_fft);
title('DFT of signal generated by upsampling');
xlabel('Frequency (Hz)');
ylabel('X(f) / N');
subplot(2, 1, 2);
plot(f, s1_fft);
title('DFT of signal generated by sampling at 24 KHz');
xlabel('Frequency (Hz)');
ylabel('X(f) / N');